format_version: 3
pipelines:
  dojo:
    group: dojo
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
        - "doc/**/*"
        - "**/*.md"
    stages:
      - build_unit:
          clean_workspace: true
          jobs:
            build_unit:
              resources:
                - docker
              artifacts:
                - build:
                    source: bin/dojo_linux_amd64
                    destination:
                - build:
                    source: bin/dojo_darwin_amd64
                    destination:
              tasks:
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile.build
                      - ./tasks deps
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile.build
                      - ./tasks build
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile.build
                      - ./tasks unit
      - e2e:
          clean_workspace: true
          jobs:
            alpine:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build_unit
                    job: build_unit
                    is_file: yes
                    source: dojo_linux_amd64
                    destination: bin
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks symlink linux
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks e2e alpine
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks test_signals alpine
            ubuntu18:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build_unit
                    job: build_unit
                    is_file: yes
                    source: dojo_linux_amd64
                    destination: bin
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks symlink linux
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks e2e ubuntu18
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks test_signals ubuntu18
      - test_images:
          clean_workspace: true
          jobs:
            linux:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build_unit
                    job: build_unit
                    is_file: yes
                    source: dojo_linux_amd64
                    destination: bin
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - ./tasks symlink linux
                - exec:
                    command: bash
                    arguments:
                        - -c
                        - cd image_scripts && ./tasks build
                - exec:
                    command: bash
                    arguments:
                        - -c
                        - cd image_scripts && ./tasks test_scripts
                - exec:
                    command: bash
                    arguments:
                        - -c
                        - cd image_scripts && ./tasks e2e
      - release:
          clean_workspace: true
          secure_variables:
            GITHUB_TOKEN: "AES:9mQGklAskrmLBczL1b/UXQ==:u/Kt5dVTpXlDIOTN7ndS6SId01ryLQK+8OorJS7ZA8EECQvc04daQkLA+gRuzHNg"
          approval:
            type: manual
          jobs:
            code:
              resources:
                - docker
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ./tasks verify_version
                - fetch:
                    stage: build_unit
                    job: build_unit
                    is_file: yes
                    source: dojo_linux_amd64
                    destination: bin
                - fetch:
                    stage: build_unit
                    job: build_unit
                    is_file: yes
                    source: dojo_darwin_amd64
                    destination: bin
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ./tasks release
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - ./tasks release_gh
